# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OLfkpbXPJhOdvwqdKtLocG3FINZh-1v8
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
iris=load_iris()
iris.data[:5]

print(iris.target_names)
['setosa' 'versicolor' 'virginica']
X=iris.data
#split the training and testing data
y=iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=41)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
KNeighborsClassifier()

y_pred = knn.predict(X_test)
knn.score(X_train, y_train), knn.score(X_test, y_test)
(0.9833333333333333, 0.9666666666666667)

confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))
