# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XSYWFFqPL3r1K2rZM7k08jirhQ_-35st
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

data=pd.read_csv("boston.csv")
data.head()

x=data.drop('medv',axis=1).values
y=data['medv'].values

x_rooms=x[:, 5]
print(x)

type(x_rooms), type(y)

x_rooms.shape, y.shape

x_rooms = x_rooms.reshape(-1,1)
y = y.reshape(-1, 1)
x_rooms.shape, y.shape

x_rooms

plt.scatter(x_rooms, y)
plt.xlabel('Number of rooms')
plt.ylabel('Value of house /1000($)')
plt.show()

reg = linear_model.LinearRegression()
reg.fit(x_rooms, y)

from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
y_pred = reg.predict(x_rooms)

print(f'MAE = {mean_absolute_error(y, y_pred)}')
print(f'MSE = {mean_squared_error(y, y_pred)}')
print(f'RMSE = {np.sqrt(mean_squared_error(y, y_pred))}')
print(f'R_2 = {r2_score(y, y_pred)}')