# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DlxUMQKtggQp3AqxMzGOkQryGoiXkuZC
"""

import pandas as pd
import numpy as np
s1=pd.Series([1,2,3,4])
print(s1)



f=np.array(['a','b','c','d'])
s2=pd.Series(f)
print(s2)

k=pd.DataFrame({
    "a": [45 , 20,6],
    "b" : ['hi', 'hello',"how are you?"]
})
print(k)

mylist = [4, 8, 12, 16, 20]
df2 = pd.DataFrame(mylist)
print(df2)

items = [['Phone', 2000], ['TV', 1500], ['Radio', 800]]
df3 = pd.DataFrame(items)
print(df3)

items = [['Phone', 2000], ['TV', 1500], ['Radio', 800]]
df4 = pd.DataFrame(items, columns=['Item', 'Price'],dtype=float)
print(df4)
df4.describe()

data = pd.read_csv('cars.csv')
print(data)

data.head()

data.tail(3)

data['disp']

print(data.loc[[0,4,7,],['cyl']])

data.loc[:,['cyl','hp']]

data.loc[:3,['cyl','hp']]